name: DJW

on:
  repository_dispatch:
    types: [run_jobs]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      job_count: ${{ steps.get-job-count.outputs.count }}
    steps:
      - name: Get job count
        id: get-job-count
        run: echo "count=${{ github.event.client_payload.job_count }}" >> $GITHUB_OUTPUT

  dynamic_job:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job_number: ${{ fromJson(format('[{0}]', join(range(needs.setup.outputs.job_count | int), ','))) }}
    steps:
      - name: Run dynamic job
        run: |
          echo "Running job number ${{ matrix.job_number }}"
          # Add your job logic here
